spring.application.name=m06-feed-busqueda
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/m06_feed
spring.datasource.username=patricia
spring.datasource.password=patricia
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.security.oauth2.resourceserver.jwt.secret=patriciasecret

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

spring.cache.type=none

springdoc.api-docs.path=/v3/api-docs
spring.h2.console.enabled=false
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
