spring.application.name=m06-feed-busqueda

# ── PostgreSQL ──────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5433/m06_feed
spring.datasource.username=patricia
spring.datasource.password=patricia
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA ─────────────────────────────────────────────────────
# update: Hibernate crea y actualiza las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ── Redis ───────────────────────────────────────────────────
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

# ── Servidor ─────────────────────────────────────────────────
server.port=8080
